##https://github.com/robodhruv/visualnav-transformer

scand_spot:
  odomtopics: ["/odom"]
  imtopics: ["/image_raw/compressed"]
  img_info: ["/camera/rgb/camera_info"]
  trackingtopics: ["/tracks_image_raw_compressed"]
  pcltopics: ["/velodyne_points"]
  scantopics: ["/scan"]
  tracking_process_func: "process_detection2d"
  camera_intrinsics: []
  ang_offset: 0.0
  process_feats: False
  process_pcl: False
  process_scan: False
  process_tracking: True
  img_process_func: "process_scand_img"
  odom_process_func: "nav_to_xy_yaw_vel" 
  scan_process_func: "ros_msg_to_json"
  pcl_process_func: "process_pointcloud2"
  start_slack: 1
  end_slack: 1

  
scand_jackal:
  odomtopics: ["/jackal_velocity_controller/odom"]
  imtopics:  ["/camera/rgb/image_raw/compressed","/left/image_color/compressed"]
  pcltopics: ["/velodyne_packets","/velodyne_points"]
  scantopics: [] #"/velodyne_2dscan","/scan"]
  trackingtopics: ["/tracks_camera_rgb_image_raw_compressed","/tracks_left_image_color_compressed"]
  img_info: ["/camera/rgb/camera_info"]
  camera_intrinsics: []
  tracking_process_func: "process_detection2d"
  ang_offset: 0.0
  process_feats: False
  process_pcl: True
  process_scan: False
  process_tracking: True
  img_process_func: "process_scand_img"
  odom_process_func: "nav_to_xy_yaw_vel" 
  scan_process_func: "ros_msg_to_json"
  pcl_process_func: "process_velodyne"
  start_slack: 1
  end_slack: 1


musohu:
  odomtopics: ["/zed2/zed_node/odom"]
  imtopics: ["/zed2/zed_node/rgb/image_rect_color/compressed"]
  trackingtopics: ["/tracks_zed2_zed_node_rgb_image_rect_color_compressed"]
  camera_intrinsics: ["/zed2/zed_node/rgb/camera_info"]
  pcltopics: ["/velodyne_points"]
  scantopics: []
  tracking_process_func: "process_detection2d"
  ang_offset: 0.0
  process_pcl: False
  process_scan: False
  process_tracking: True
  img_process_func: "process_scand_img"
  odom_process_func: "nav_to_xy_yaw_vel" 
  scan_process_func: "ros_msg_to_json"
  pcl_process_func: "process_pointcloud2"
  start_slack: 1
  end_slack: 1
  img_frame: "zed2_left_camera_optical_frame"
  lidar_frame: "lidar_link"


# add your own datasets below:
go2nus:
  odomtopics: ["/utlidar/robot_odom"]
  imtopics: ["/camera/camera/color/image_raw/compressed"]
  camera_intrinsics: ["/camera/camera/color/camera_info"]
  pcltopics: ["/rslidar_points"]
  scantopics: []
  trackingtopics: ["/tracks_camera_camera_color_image_raw_compressed"]
  ang_offset: 0.0
  process_pcl: True
  process_scan: False
  process_tracking: False
  img_process_func: "process_nus_dog_img"
  odom_process_func: "nav_to_xyz_yaw" 
  scan_process_func: ""
  pcl_process_func: "process_pointcloud2_with_intensity"
  tracking_process_func: "process_detection2d"
  start_slack: 1
  end_slack: 1
gmu: 
  odomtopics: ["/odom"]
  imtopics: ["/zed2/zed_node/rgb/image_rect_color/compressed"]
  camera_intrinsics: ["/zed2/zed_node/rgb/camera_info"]
  pcltopics: ["/velodyne_points"]
  scantopics: []
  trackingtopics: ["/tracks_zed2_zed_node_rgb_image_rect_color_compressed"]
  ang_offset: 0.0
  process_pcl: True
  process_scan: False
  process_tracking: True
  img_process_func: "process_scand_img"
  odom_process_func: "nav_to_xy_yaw_vel" 
  scan_process_func: ""
  pcl_process_func: "process_pointcloud2"
  tracking_process_func: "process_detection2d"
  start_slack: 1
  end_slack: 1
uex: 
  odomtopics: ["/zed/zed_node/odom"]
  imtopics: ["/camera_360/image/compressed","/zed/zed_node/rgb/image_rect_color/compressed"]
  camera_intrinsics: ["/zed/zed_node/rgb/camera_info"]
  pcltopics: ["/rslidar_helios_points"]
  scantopics: []
  trackingtopics: ["/tracks_camera_360_image_compressed","/tracks_zed_zed_node_rgb_image_rect_color_compressed"]
  ang_offset: 0.0
  process_pcl: True
  process_scan: False
  process_tracking: True
  img_process_func: "process_scand_img"
  odom_process_func: "nav_to_xy_yaw_vel" 
  scan_process_func: ""
  pcl_process_func: "process_pointcloud2"
  tracking_process_func: "process_detection2d"
  start_slack: 1
  end_slack: 1
