robot_name: "go2"

### lidar range configuration params ###
LIDAR_RANGE_METERS: 10.0
LIDAR_HEIGHT_METERS: 5.0
RESOLUTION: 0.05

### Spot robot configuration ###
kMaxLinearSpeed: 1.6 #m/s

### Joystick configuration for the rosbag ###
### USING THE DualShock 4 Joystick ###
kXAxis: 4
kYAxis: 3
kRAxis: 0
kSitBtn: 0
kStandBtn: 2

### base_local_planner_params.yaml
max_vel_x: 0.45
min_vel_x: 0.1
max_vel_theta: 1.0
min_in_place_vel_theta: 0.4

acc_lim_theta: 3.2
acc_lim_x: 2.5
acc_lim_y: 2.5

holonomic_robot: false

### costmap_common_params.yaml
# Go2 robot footprint (approximate dimensions for Unitree Go2)
footprint: [[-0.35, -0.165], [-0.35, 0.165], [0.35, 0.165], [0.35, -0.165]]

