robot_name: "miraikan"

### lidar range configuration params ###
LIDAR_RANGE_METERS: 10.0
LIDAR_HEIGHT_METERS: 5.0
RESOLUTION: 0.05

### Robot configuration ###
kMaxLinearSpeed: 1.6 #m/s

### Joystick configuration for the rosbag ###
kXAxis: 4
kYAxis: 3
kRAxis: 0
kSitBtn: 0
kStandBtn: 2

### base_local_planner_params.yaml
max_vel_x: 1.6
min_vel_x: 0.2
max_vel_theta: 1.57
min_in_place_vel_theta: 0.314

acc_lim_theta: 20.0
acc_lim_x: 2.5
acc_lim_y: 2.5

holonomic_robot: false

### costmap_common_params.yaml
# Robot footprint - adjust based on actual robot dimensions
footprint: [[-0.3, -0.2], [-0.3, 0.2], [0.3, 0.2], [0.3, -0.2]]
