
# global params for diffusion model
# normalized min and max
action_stats:
  min: [-2.5, -4] # [min_dx, min_dy]
  max: [5, 4] # [max_dx, max_dy]

# data specific params
recon:
  metric_waypoint_spacing: 0.25 # average spacing between waypoints (meters)

  # OPTIONAL (FOR VISUALIZATION ONLY)
  camera_metrics: # https://docs.opencv.org/4.x/dc/dbb/tutorial_py_calibration.html
    camera_height: 0.95 # meters
    camera_x_offset: 0.45 # distance between the center of the robot and the forward facing camera
    camera_matrix:
      fx: 272.547000
      fy: 266.358000
      cx: 320.000000
      cy: 220.000000
    dist_coeffs:
      k1: -0.038483
      k2: -0.010456
      p1: 0.003930
      p2: -0.001007
      k3: 0.0

scand:
  metric_waypoint_spacing: 0.38
  
  # OPTIONAL (FOR VISUALIZATION ONLY)
  camera_metrics: # https://docs.opencv.org/4.x/dc/dbb/tutorial_py_calibration.html
    camera_height: 0.95 # meters
    camera_x_offset: 0.45 # distance between the center of the robot and the forward facing camera
    camera_matrix:
      fx: 272.547000
      fy: 266.358000
      cx: 320.000000
      cy: 220.000000
    dist_coeffs:
      k1: -0.038483
      k2: -0.010456
      p1: 0.003930
      p2: -0.001007
      k3: 0.0
    
go2nus: 
  metric_waypoint_spacing: 0.175
  # OPTIONAL (FOR VISUALIZATION ONLY)
  camera_metrics: # https://docs.opencv.org/4.x/dc/dbb/tutorial_py_calibration.html
    camera_height: 0.95 # meters
    camera_x_offset: 0.45 # distance between the center of the robot and the forward facing camera
    camera_matrix:
      fx: 607.6533813476562
      fy: 607.3688354492188
      cx: 420.5920104980469
      cy: 247.97695922851562
    dist_coeffs:
      k1: 0.0
      k2: 0.0
      p1: 0.0
      p2: 0.0
      k3: 0.0
  pedmap:
    size: 20 #20m x 20m
    resolution: 0.25 # 0.25m/pixel
  goal_distance: 10 # meters
  sample_rate: 4 # Hz