version: '3.8'

services:
  data_sampling:
    build: .
    container_name: data_sampling
    volumes:
      # Mount rosbag directory (update this path to the root of where your ros2 bags are stored)
      # Change the left side to your actual rosbag directory path
      - /data2/SBPD-dataset/SBPD/Bag/dataset-bag-miraikan-fixed:/ros2_bags:ro
      # Mount output directory for results
      - /data2/SBPD-dataset/SBPD/Bag_processed/miraikan_fix_zipped:/processed
      - .:/workspace
      # Mount the current directory to sync with container
    network_mode: host
    stdin_open: true
    tty: true
